"""restructure_db_3_tables

Revision ID: b3fa553fab7c
Revises: 001
Create Date: 2025-11-21 09:58:13.163402+01:00

"""
from alembic import op
import sqlalchemy as sa


# Identifiants de révision
revision = 'b3fa553fab7c'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Applique les changements de schéma."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entreprises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('comptes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('lot', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_facture', sa.Integer(), nullable=False),
    sa.Column('compte_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('abo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('conso', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remise', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compte_id', 'date', name='uix_compte_date')
    )
    op.drop_index(op.f('ix_record_numero_compte'), table_name='record')
    op.drop_index(op.f('ix_record_numero_facture'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_ligne_numero_acces'), table_name='ligne')
    op.drop_table('ligne')
    op.drop_table('entreprise')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annule les changements de schéma."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entreprise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('ligne',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=255), nullable=True),
    sa.Column('type_ligne', sa.VARCHAR(length=50), nullable=False),
    sa.Column('numero_acces', sa.VARCHAR(length=100), nullable=False),
    sa.Column('adresse', sa.VARCHAR(length=500), nullable=True),
    sa.Column('entreprise_id', sa.INTEGER(), nullable=False),
    sa.CheckConstraint("type_ligne IN ('Internet', 'Internet bas debit', 'Mobile', 'Fixe', 'Fixe secondaire', 'Autre')"),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_acces')
    )
    op.create_index(op.f('ix_ligne_numero_acces'), 'ligne', ['numero_acces'], unique=1)
    op.create_table('record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ligne_id', sa.INTEGER(), nullable=False),
    sa.Column('numero_compte', sa.VARCHAR(length=100), nullable=False),
    sa.Column('numero_facture', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('mois', sa.VARCHAR(length=50), nullable=False),
    sa.Column('abo', sa.FLOAT(), nullable=False),
    sa.Column('conso', sa.FLOAT(), nullable=False),
    sa.Column('remise', sa.FLOAT(), nullable=False),
    sa.Column('total_ht', sa.FLOAT(), nullable=False),
    sa.Column('total_ttc', sa.FLOAT(), nullable=False),
    sa.Column('nb_lignes_detail', sa.INTEGER(), nullable=False),
    sa.Column('statut', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ligne_id'], ['ligne.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_numero_facture'), 'record', ['numero_facture'], unique=False)
    op.create_index(op.f('ix_record_numero_compte'), 'record', ['numero_compte'], unique=False)
    op.drop_table('factures')
    op.drop_table('comptes')
    op.drop_table('entreprises')
    # ### end Alembic commands ###
